# Process heterozygosity. Take per-individual heterozygosity estimates (across scaffolds/chromosomes)
# and outputs values per individual. This script takes as input an output file generated by calc_heterozygosity.R

library(tidyverse)

# Here we will output heterozygosity values per individual, and compare estimates that include and do not include the 
# Z chromosome. 

# vcf order 

# Setophaga_graciae_CM_S10255_BEL	Setophaga_graciae_CM_S9116_BEL	
# Setophaga_graciae_DMNS_52524_COL Setophaga_graciae_KU_33633_RACN	
# Setophaga_graciae_KU_33634_RACN	Setophaga_graciae_KU_8199_SANA	
# Setophaga_graciae_KU_8218_SANA	Setophaga_graciae_UWBM_105736_ARI	
# Setophaga_graciae_UWBM_106758_NM Setophaga_graciae_UWBM_106760_NM
# Setophaga_graciae_UWBM_108714_NEV	Setophaga_graciae_UWBM_111891_NM	
# Setophaga_graciae_UWBM_111896_NM	Setophaga_graciae_UWBM_112575_GUE	
# Setophaga_graciae_UWBM_112576_GUE	Setophaga_graciae_UWBM_112587_GUE	
# Setophaga_graciae_UWBM_112592_GUE	Setophaga_graciae_UWBM_113059_CHI	
# Setophaga_graciae_UWBM_113126_CHI	Setophaga_graciae_UWBM_113970_DUR	
# Setophaga_graciae_UWBM_114011_DUR Setophaga_graciae_UWBM_114012_DUR 
# Setophaga_graciae_UWBM_114019_DUR Setophaga_graciae_UWBM_114038_DUR	
# Setophaga_graciae_UWBM_114039_DUR Setophaga_graciae_UWBM_114046_DUR 
# Setophaga_graciae_UWBM_114047_DUR	Setophaga_graciae_UWBM_114087_CHIH 
# Setophaga_graciae_UWBM_114088_CHIH Setophaga_graciae_UWBM_114090_CHIH 
# Setophaga_graciae_UWBM_114091_CHIH Setophaga_graciae_UWBM_114126_CHIH 
# Setophaga_graciae_UWBM_114127_CHIH Setophaga_graciae_UWBM_114128_CHIH 
# Setophaga_graciae_UWBM_114282_NEV Setophaga_graciae_UWBM_114424_NEV 
# Setophaga_graciae_UWBM_115308_GUE Setophaga_graciae_UWBM_69981_PCA 
# Setophaga_graciae_UWBM_77653_ARI Setophaga_graciae_UWBM_77735_ARI 
# Setophaga_graciae_UWBM_84639_ARI Setophaga_graciae_UWBM_93801_CPN 
# Setophaga_graciae_UWBM_93805_CPN Setophaga_graciae_UWBM_93806_CPN 
# Setophaga_graciae_UWBM_93807_CPN Setophaga_graciae_UWBM_93808_CPN 
# Setophaga_graciae_UWBM_95850_ARI

# input 

output <- read.table("output.het.txt", sep = "\t", header = T)


het <- c()

# calculate heterozygosity
for (i in 2:48){
  # sum het sites/sum total sites
  het[i] <- (sum(output[,i+47])/sum(output[,i]))
}

# export estimates in table

# extract individual names using gsub, and dropping '_total_sites' from suffix 

individual_names <- gsub("_total_sites", "", colnames(output)[2:48])

# combine individual names as rows and het estimates as column

het_table <- as_tibble(cbind(individual_names, het[-1]))

# convert het column to numeric, and provide a name 

het_table$V2 <- as.numeric(het_table$V2)

colnames(het_table)[2] <- c("heterozygosity")

# export het_table 

write.table(het_table, file = "het_table_with_z.txt")


## same process as above, but this time remove regions that map to Z 
# remove Z regions

output_no_z <- output[-102:-109,]

# remove Z chromosome regions, and repeat process

het_no_z <- c()

# calculate heterozygosity
for (i in 2:48){
  # sum het sites/sum total sites
  het_no_z[i] <- (sum(output_no_z[,i+47])/sum(output_no_z[,i]))
}

# export estimates in table

# extract individual names using gsub, and dropping '_total_sites' from suffix 

individual_names <- gsub("_total_sites", "", colnames(output_no_z)[2:48])

# combine individual names as rows and het estimates as column

het_table_no_z <- as_tibble(cbind(individual_names, het_no_z[-1]))

# convert het column to numeric, and provide a name 

het_table_no_z$V2 <- as.numeric(het_table_no_z$V2)

colnames(het_table_no_z)[2] <- c("heterozygosity")

# export het_table 

write.table(het_table_no_z, file = "het_table_no_z.txt")

# assess relationship between estimates with and without Z chromosome 

plot(het_table$heterozygosity, het_table_no_z$heterozygosity, 
     xlab = "Heterozygosity_Z", ylab = "Heterozygosity_no_Z")


# import het dataset (calculated using excel spreadsheet), to compare estimates with the estimates calculated here

het_ne_dataset <- read.csv("het_ne_roh.csv", sep = ",")

colnames(het_ne_dataset)[1] <- "individual_names"

het_ne_datset <- as_tibble(het_ne_dataset)

# assess relationship with estimates calculated with excel spreadsheet (need to combine them into one dataset, joined by name)

combined_dataset <- merge(het_table, het_ne_dataset, by = "individual_names")

combined_dataset_no_z <- merge(combined_dataset, het_table_no_z, by = "individual_names")

plot(combined_dataset_no_z$heterozygosity.y, combined_dataset_no_z$heterozygosity.x)

plot(combined_dataset_no_z$heterozygosity, combined_dataset_no_z$heterozygosity.x)

plot(combined_dataset_no_z$heterozygosity, combined_dataset_no_z$heterozygosity.y)



